# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ffeea8a8f7f48a2d3efd2275ef8f89c0d2bc086d31f1b3d295dc709f7a39c3c7f0ddd58afdd4679d5c8072401f603af145081db1c3e572c460d6742e425bd6ac

test:
  secret_key_base: 012e31f60770fdf8b746f776929f9f4ab98d8eceb5e6adc3afe64faff4631a430aacb248215aa5a277fd3fcc8bb3101f1643bddf98a11a0f220b6fd6e35a9b74

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
