# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Area.create!([{name: 'AdministrativoA'},{name: 'Investigación y DesarrolloA'},{name: 'Atención al ClienteA'},{name: 'ComercialA'},
				{name: 'AdministrativoB'},{name: 'Investigación y DesarrolloB'},{name: 'Atención al ClienteB'},{name: 'ComercialB'},
				{name: 'AdministrativoC'},{name: 'Investigación y DesarrolloC'},{name: 'Atención al ClienteC'},{name: 'ComercialC'},
				{name: 'AdministrativoD'},{name: 'Investigación y DesarrolloD'},{name: 'Atención al ClienteD'},{name: 'ComercialD'},
				{name: 'AdministrativoE'},{name: 'Investigación y DesarrolloE'},{name: 'Atención al ClienteE'},{name: 'ComercialE'},
				{name: 'AdministrativoF'},{name: 'Investigación y DesarrolloF'},{name: 'Atención al ClienteF'},{name: 'ComercialF'},
				{name: 'AdministrativoG'},{name: 'Investigación y DesarrolloG'},{name: 'Atención al ClienteG'},{name: 'ComercialG'},
				{name: 'AdministrativoH'},{name: 'Investigación y DesarrolloH'},{name: 'Atención al ClienteH'},{name: 'ComercialH'},
				{name: 'AdministrativoI'},{name: 'Investigación y DesarrolloI'},{name: 'Atención al ClienteI'},{name: 'ComercialI'},
				{name: 'AdministrativoJ'},{name: 'Investigación y DesarrolloJ'},{name: 'Atención al ClienteJ'},{name: 'ComercialJ'},
				{name: 'AdministrativoK'},{name: 'Investigación y DesarrolloK'},{name: 'Atención al ClienteK'},{name: 'ComercialK'},
				{name: 'AdministrativoL'},{name: 'Investigación y DesarrolloL'},{name: 'Atención al ClienteL'},{name: 'ComercialL'},
				{name: 'AdministrativoM'},{name: 'Investigación y DesarrolloM'},{name: 'Atención al ClienteM'},{name: 'ComercialM'},
				{name: 'AdministrativoN'},{name: 'Investigación y DesarrolloN'},{name: 'Atención al ClienteN'},{name: 'ComercialN'},
				{name: 'AdministrativoO'},{name: 'Investigación y DesarrolloO'},{name: 'Atención al ClienteO'},{name: 'ComercialO'},
				{name: 'AdministrativoP'},{name: 'Investigación y DesarrolloP'},{name: 'Atención al ClienteP'},{name: 'ComercialP'},
				{name: 'AdministrativoQ'},{name: 'Investigación y DesarrolloQ'},{name: 'Atención al ClienteQ'},{name: 'ComercialQ'},
				{name: 'AdministrativoR'},{name: 'Investigación y DesarrolloR'},{name: 'Atención al ClienteR'},{name: 'ComercialR'},
				{name: 'AdministrativoS'},{name: 'Investigación y DesarrolloS'},{name: 'Atención al ClienteS'},{name: 'ComercialS'},
				{name: 'AdministrativoT'},{name: 'Investigación y DesarrolloT'},{name: 'Atención al ClienteT'},{name: 'ComercialT'},
				{name: 'AdministrativoU'},{name: 'Investigación y DesarrolloU'},{name: 'Atención al ClienteU'},{name: 'ComercialU'},
				{name: 'AdministrativoV'},{name: 'Investigación y DesarrolloV'},{name: 'Atención al ClienteV'},{name: 'ComercialV'},
				{name: 'AdministrativoW'},{name: 'Investigación y DesarrolloW'},{name: 'Atención al ClienteW'},{name: 'ComercialW'},
				{name: 'AdministrativoX'},{name: 'Investigación y DesarrolloX'},{name: 'Atención al ClienteX'},{name: 'ComercialX'},
				{name: 'AdministrativoY'},{name: 'Investigación y DesarrolloY'},{name: 'Atención al ClienteY'},{name: 'ComercialY'}])
Position.create!([{name: 'Gerente GeneralA'},{name: 'Gerente ComercialA'},{name: 'Director de I+DA'},{name: 'Director de Atención al ClienteA'},
					{name: 'Gerente GeneralB'},{name: 'Gerente ComercialB'},{name: 'Director de I+DB'},{name: 'Director de Atención al ClienteB'},
					{name: 'Gerente GeneralC'},{name: 'Gerente ComercialC'},{name: 'Director de I+DC'},{name: 'Director de Atención al ClienteC'},
					{name: 'Gerente GeneralD'},{name: 'Gerente ComercialD'},{name: 'Director de I+DD'},{name: 'Director de Atención al ClienteD'},
					{name: 'Gerente GeneralE'},{name: 'Gerente ComercialE'},{name: 'Director de I+DE'},{name: 'Director de Atención al ClienteE'},
					{name: 'Gerente GeneralF'},{name: 'Gerente ComercialF'},{name: 'Director de I+DF'},{name: 'Director de Atención al ClienteF'},
					{name: 'Gerente GeneralG'},{name: 'Gerente ComercialG'},{name: 'Director de I+DG'},{name: 'Director de Atención al ClienteG'},
					{name: 'Gerente GeneralH'},{name: 'Gerente ComercialH'},{name: 'Director de I+DH'},{name: 'Director de Atención al ClienteH'},
					{name: 'Gerente GeneralI'},{name: 'Gerente ComercialI'},{name: 'Director de I+DI'},{name: 'Director de Atención al ClienteI'},
					{name: 'Gerente GeneralJ'},{name: 'Gerente ComercialJ'},{name: 'Director de I+DJ'},{name: 'Director de Atención al ClienteJ'},
					{name: 'Gerente GeneralK'},{name: 'Gerente ComercialK'},{name: 'Director de I+DK'},{name: 'Director de Atención al ClienteK'},
					{name: 'Gerente GeneralL'},{name: 'Gerente ComercialL'},{name: 'Director de I+DL'},{name: 'Director de Atención al ClienteL'},
					{name: 'Gerente GeneralM'},{name: 'Gerente ComercialM'},{name: 'Director de I+DM'},{name: 'Director de Atención al ClienteM'},
					{name: 'Gerente GeneralN'},{name: 'Gerente ComercialN'},{name: 'Director de I+DN'},{name: 'Director de Atención al ClienteN'},
					{name: 'Gerente GeneralO'},{name: 'Gerente ComercialO'},{name: 'Director de I+DO'},{name: 'Director de Atención al ClienteO'},
					{name: 'Gerente GeneralP'},{name: 'Gerente ComercialP'},{name: 'Director de I+DP'},{name: 'Director de Atención al ClienteP'},
					{name: 'Gerente GeneralQ'},{name: 'Gerente ComercialQ'},{name: 'Director de I+DQ'},{name: 'Director de Atención al ClienteQ'},
					{name: 'Gerente GeneralR'},{name: 'Gerente ComercialR'},{name: 'Director de I+DR'},{name: 'Director de Atención al ClienteR'},
					{name: 'Gerente GeneralS'},{name: 'Gerente ComercialS'},{name: 'Director de I+DS'},{name: 'Director de Atención al ClienteS'},
					{name: 'Gerente GeneralT'},{name: 'Gerente ComercialT'},{name: 'Director de I+DT'},{name: 'Director de Atención al ClienteT'},
					{name: 'Gerente GeneralU'},{name: 'Gerente ComercialU'},{name: 'Director de I+DU'},{name: 'Director de Atención al ClienteU'},
					{name: 'Gerente GeneralV'},{name: 'Gerente ComercialV'},{name: 'Director de I+DV'},{name: 'Director de Atención al ClienteV'},
					{name: 'Gerente GeneralW'},{name: 'Gerente ComercialW'},{name: 'Director de I+DW'},{name: 'Director de Atención al ClienteW'},
					{name: 'Gerente GeneralX'},{name: 'Gerente ComercialX'},{name: 'Director de I+DX'},{name: 'Director de Atención al ClienteX'},
					{name: 'Gerente GeneralY'},{name: 'Gerente ComercialY'},{name: 'Director de I+DY'},{name: 'Director de Atención al ClienteY'}])
Concept.create!([{concept_name: 'Salario', category: 'Devengado'},{concept_name: 'Auxilio de Transporte', category: 'Devengado'},
	{concept_name: 'Salud', category: 'Deducido'},{concept_name: 'Pensión', category: 'Deducido'},{concept_name: 'Vacaciones', category: 'Provisión'},
	{concept_name: 'Prima', category: 'Provisión'},{concept_name: 'Cesantías', category: 'Provisión'},{concept_name: 'Intereses de Cesantías', category: 'Provisión'}])
Fond.create!([{document_type: 'NIT', document_number: '12345', business_name: 'Compensar', type_of_fond: 'CajaComp'},
				{document_type: 'NIT', document_number: '67890', business_name: 'Positiva', type_of_fond: 'ARL'},
				{document_type: 'NIT', document_number: '13579', business_name: 'Protección', type_of_fond: 'Cesantias'},
				{document_type: 'NIT', document_number: '24680', business_name: 'Colpensiones', type_of_fond: 'Pensiones'},
				{document_type: 'NIT', document_number: '54321', business_name: 'Compensar', type_of_fond: 'EPS'},
				{document_type: 'NIT', document_number: '98760', business_name: 'Colsubsidio', type_of_fond: 'CajaComp'},
				{document_type: 'NIT', document_number: '55555', business_name: 'Sura', type_of_fond: 'ARL'},
				{document_type: 'NIT', document_number: '63451', business_name: 'Porvenir', type_of_fond: 'Cesantias'},
				{document_type: 'NIT', document_number: '22222', business_name: 'Colfondos', type_of_fond: 'Pensiones'},
				{document_type: 'NIT', document_number: '12679', business_name: 'Sanitas', type_of_fond: 'EPS'}])
Employee.create!([{document_type: 'CC', document_number: '123', first_name: 'Andrew', other_name: 'James', last_name: 'Walkan', second_surname: 'Junior',
	birthdate: '01/02/1980', birthplace: 'Astana', address: 'Calle falsa 123', phones: '3213213213', email: 'ajwj@correo.com', admission_date: '01/01/2017', 
	salary: 2000000, transport_aid: false, integral_salary: false, area_id: 1, position_id: 1},
	{document_type: 'CC', document_number: '456', first_name: 'Lucas', other_name: 'Leonardo', last_name: 'Achilier', second_surname: 'Villegas',
	birthdate: '01/07/1984', birthplace: 'Cali', address: 'Calle falsa 456', phones: '3213453453', email: 'llav@correo.com', admission_date: '01/01/2017', 
	salary: 1500000, transport_aid: false, integral_salary: false, area_id: 2, position_id: 2},
	{document_type: 'CC', document_number: '789', first_name: 'Takashi', other_name: '', last_name: 'Yamada', second_surname: 'Perdida',
	birthdate: '01/12/1978', birthplace: 'Sapporo', address: 'Calle falsa 789', phones: '3217498539', email: 'twp@correo.com', admission_date: '01/01/2015', 
	salary: 4000000, transport_aid: false, integral_salary: false, area_id: 3, position_id: 3},
	{document_type: 'CC', document_number: '555', first_name: 'Gerard', other_name: '', last_name: 'López', second_surname: 'Sánchez',
	birthdate: '01/05/1985', birthplace: 'Madrid', address: 'Calle falsa 555', phones: '3218589656', email: 'gls@correo.com', admission_date: '01/01/2017', 
	salary: 900000, transport_aid: true, integral_salary: false, area_id: 4, position_id: 4},
	{document_type: 'CC', document_number: '333', first_name: 'Orlando', other_name: 'Alberto', last_name: 'Luna', second_surname: 'Parra',
	birthdate: '01/08/1975', birthplace: 'Bogota', address: 'Calle falsa 333', phones: '3218784444', email: 'oalp@correo.com', admission_date: '01/01/2010', 
	salary: 12000000, transport_aid: false, integral_salary: true, area_id: 5, position_id: 5}])
FondEmployee.create!([{fond_id: 1, employee_id: 1},{fond_id: 2, employee_id: 1},{fond_id: 3, employee_id: 1},{fond_id: 4, employee_id: 1},{fond_id: 5, employee_id: 1},
						{fond_id: 6, employee_id: 2},{fond_id: 7, employee_id: 2},{fond_id: 8, employee_id: 2},{fond_id: 9, employee_id: 2},{fond_id: 10, employee_id: 2},
						{fond_id: 1, employee_id: 3},{fond_id: 2, employee_id: 3},{fond_id: 3, employee_id: 3},{fond_id: 4, employee_id: 3},{fond_id: 5, employee_id: 3},
						{fond_id: 6, employee_id: 4},{fond_id: 7, employee_id: 4},{fond_id: 8, employee_id: 4},{fond_id: 9, employee_id: 4},{fond_id: 10, employee_id: 4},
						{fond_id: 1, employee_id: 5},{fond_id: 2, employee_id: 5},{fond_id: 3, employee_id: 5},{fond_id: 4, employee_id: 5},{fond_id: 5, employee_id: 5}])
PaydayMaster.create!([{payday_type: 'Nomina', payday_date: '15/01/2017', description: 'tengo frio'},
						{payday_type: 'Vacaciones', payday_date: '20/01/2017', description: 'tengo frio'},
						{payday_type: 'Nomina', payday_date: '31/01/2017', description: 'tengo frio'},
						{payday_type: 'Nomina', payday_date: '15/02/2017', description: 'tengo frio'},
						{payday_type: 'Terminacion', payday_date: '20/02/2017', description: 'tengo frio'}])
Vacation.create!([{paid_days: 15, taken_days: 17, start_date: '20/01/2017', end_date: '04/02/2017', employee_id: 5, payday_master_id: 2}])
PaydayDetail.create!([{base_value: 1000000, win: 1000000, loss: 0, appropiation: 0, worked_days: 15, initial_date: '01/01/2017', final_date: '15/01/2017',
				concept_id: 1, employee_id: 1, payday_master_id: 1},{base_value: 1000000, win: 1000000, loss: 0, appropiation: 0, worked_days: 15, 
				initial_date: '20/01/2017', final_date: '05/02/2017', concept_id: 1, employee_id: 2, payday_master_id: 2},{base_value: 1000000, win: 1000000, 
				loss: 0, appropiation: 0, worked_days: 15, initial_date: '01/02/2017', final_date: '15/02/2017', concept_id: 1, employee_id: 4, 
				payday_master_id: 4},{base_value: 1000000, win: 1000000, loss: 0, appropiation: 0, worked_days: 15, initial_date: '16/01/2017', 
				final_date: '31/01/2017', concept_id: 1, employee_id: 3, payday_master_id: 3},{base_value: 1000000, win: 1000000, loss: 0, appropiation: 0, 
				worked_days: 15, initial_date: '20/02/2017', final_date: '20/02/2017', concept_id: 1, employee_id: 5, payday_master_id: 5}])
Novelty.create!([{novelty_type: 'Inactividad', category: 'Devengado', novelty_value: 0, period: 1, applied: 0, description: 'Enfermedad General', 
	percentage1: 100, percentage2: 66.67, percentage3: 50, employee_id: 1, payday_details_id: 5},{novelty_type: 'Otros', category: 'Devengado', 
	novelty_value: 100000, period: 1, applied: 1, description: 'Bonificacion', percentage1: 0, percentage2: 0, percentage3: 0, employee_id: 5, 
	payday_details_id: 3}])
User.create!([{username: 'ajwj', password: '123456', role: 'EMPLEADO', employee_id: 1},{username: 'llav', password: '12345', role: 'EMPLEADO', employee_id: 2},
		{username: 'twp', password: '1234567', role: 'EMPLEADO', employee_id: 3},{username: 'gls', password: '12345678', role: 'ADMIN', employee_id: 4},
		{username: 'oalp', password: '1234', role: 'ADMIN', employee_id: 5}])
Option.create!([{action: 'Liquidar', insert_action: true, update_action: false, delete_action: true},
				{action: 'Empleados', insert_action: true, update_action: true, delete_action: true},
				{action: 'Estadisticas', insert_action: false, update_action: false, delete_action: false}])
Log.create!([{log_time: '01/02/2017', user_id: 4, option_id: 1}])
